comparison_interface/routes.py
"""Handles all the URL routing."""

from flask import Blueprint, current_app, request, session

from .views.ethics import Ethics
from .views.introduction import Introduction
from .views.item_preference import ItemsPreference
from .views.logout import Logout
from .views.policies import Policies
from .views.rank import Rank
from .views.register import Register
from .views.request import Request
from .views.thankyou import Thankyou

blueprint = Blueprint('views', __name__, template_folder='templates')


@blueprint.after_request
def add_no_cache_headers(response):
    """Add no cache headers to all pages."""
    response.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = 0
    return response


@blueprint.route('/introduction', methods=['GET'])
def introduction():
    """Handle introduction URL."""
    return Request.process(Introduction(current_app, session), request)


@blueprint.route('/ethics-agreement', methods=['GET'])
def ethics_agreement():
    """Handle ethics agreement URL."""
    return Request.process(Ethics(current_app, session), request)


@blueprint.route('/policies', methods=['GET'])
def policies():
    """Handle policies URL."""
    return Request.process(Policies(current_app, session), request)


@blueprint.route('/', methods=['GET', 'POST'])
@blueprint.route('/register', methods=['GET', 'POST'])
def user_registration():
    """Handle registration URL and the route location when no user session registered."""
    return Request.process(Register(current_app, session), request)


@blueprint.route('/selection/items', methods=['GET', 'POST'])
def item_selection():
    """Handle item selection URL (pre-ranking)."""
    return Request.process(ItemsPreference(current_app, session), request)


@blueprint.route('/rank', methods=['GET', 'POST'])
def rank():
    """Handle ranking URL."""
    return Request.process(Rank(current_app, session), request)


@blueprint.route('/logout', methods=['GET'])
def logout():
    """Handle logout URL."""
    return Request.process(Logout(current_app, session), request)


@blueprint.route('/thankyou', methods=['GET'])
def thankyou():
    """Handle thankyou/escape route URL."""
    return Request.process(Thankyou(current_app, session), request)

comparison_interface/templates/204.html
{% extends "layout.html" %}

{% block page_title %}: {{ error_204_title }}{% endblock %}

{% block content %}
    <div class="p-5 mb-4">
        <div class="text-center">
            <h1>204</h1>
            <p>{{ error_204_message }}</p>
            <p><a href="{{ url_for('.logout') }}">{{ logout_page_title }}</a></p>
        </div>
    </div>
{% endblock %}

comparison_interface/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="data:">

    <title>{{ website_title }}{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom-style.css') }}">
    {% block css %}
    {% endblock %}

  </head>

  <body>
    {% if render_cookie_banner %}
      <section id="cookie-message"></section>
    {% endif %}
    <nav class="navbar navbar-expand-md p-2 mb-2 fs-5" style="background-color: lightgray">
      <a class="visually-hidden-focusable rounded-2 p-1 bg-white" href="#main">Skip to main content</a>
     {{ website_title }}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main-navigation" aria-controls="main-navigation" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="main-navigation">
        <ul class="navbar-nav ms-md-auto">
          {% if render_user_instructions %}
            <li class="nav-item">
              <a class="nav-link focus-ring mx-2" href="{{ url_for('views.introduction') }}">{{introduction_page_title}}</a>
            </li>
          {% endif %}
          {% if render_user_ethics_agreement %}
            <li class="nav-item">
              <a class="nav-link focus-ring mx-2" href="{{ url_for('views.ethics_agreement') }}">{{ethics_agreement_page_title}}</a>
            </li>
          {% endif %}
          {% if render_site_policies %}
            <li class="nav-item">
              <a class="nav-link focus-ring mx-2" href="{{ url_for('views.policies') }}">{{policies_page_title}}</a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link focus-ring ml-2" href="{{ url_for('views.logout') }}">{{logout_page_title}}</a>
          </li>
        </ul>
      </div>
    </nav>

    <main id="main">
      <div id="content">{% block content %}{% endblock %}</div>
    </main>
    <footer>
      
    </footer>

    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ url_for('static', filename='js/jquery-3.7.1.slim.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/src/iframe-change.js') }}"></script>
    <script src="{{ url_for('static', filename='js/src/user-registry-validation.js') }}"></script>
    <script src="{{ url_for('static', filename='js/src/rank-control.js') }}"></script>
    <script src="{{ url_for('static', filename='js/src/prevent-double-click.js') }}"></script>
    {% if render_cookie_banner %}
      <script>
        function getCookie(name) {
            // Convert cookies string to list
            var c_list = document.cookie.split("; "),
                i = 0,
                c,
                c_name,
                c_value;
            // Loop through cookies list to find a match
            for (i = 0; i < c_list.length; i++) {
                // Find cookie
                c = c_list[i].split('=');
                c_name = c[0];
                c_value = c[1];
                // Return cookie value if cookie name matches
                if (c_name === name) {
                    return c_value;
                }
            }
            // If no cookie found with given name, return null
            return null;
        }


        // Show a message about cookies to user if they have not yet agreed

        document.cookie = '';

        // If user hasn't yet agreed to cookies
        if (getCookie('cookieMessageApprove') !== '1') {

            // Generate HTML message
            var html_to_inject = '\
        <div id="cookie-message-popup" style="text-align: center; background: #343a40; padding: 1em; color: white;">\
          <div id="cookie-title">{{site_cookies_title}}</div>\
        {{site_cookies_text|safe}}<button id="cookie-message-popup-accept" style="display: inline-block; background: white; color: black; padding: 0.4em 1.7em; margin-left: 1em; cursor: pointer; vertical-align: middle;">{{site_cookies_accept_button_label}}</button>\
        </div>';

            // Add the HTML message to the page

            document.getElementById('cookie-message').innerHTML += html_to_inject;
            document.getElementById('cookie-message').setAttribute('aria-labelledby', 'cookie-title');
        }

        // Add event listener for 'accept' button to set the cookie and hide the message
        try {
            document.getElementById("cookie-message-popup-accept").addEventListener("click", function () {
                document.cookie = "cookieMessageApprove=1; expires=Mon, 31 Dec 2040 23:59:59 GMT; path=/; Secure;";
                document.getElementById("cookie-message-popup").style.display = "none";
            });
        } catch (ignore) {
            // Ignore error, as it's expected to fail when user has already approved (as cookie popup won't show)
        }
      </script>
      {% endif %}
    {% block js %}{% endblock %}
  </body>
</html>